image: node:16

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
    - mv build ../public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - mv public/ ./public
  artifacts:
    paths:
      - public
    expire_in: 30 days